### ISSUE TITLE
How to make xAxis with String Values?

### ISSUE THREAD

**Issue by megifernanda** [linheimx/LChart#10]
sir how to make yAxis with String Values?

**Comment by linheimx** [comment]
you can set ValueAdapter for yAxis，like this:
```
 yAxis.set_ValueAdapter(new IValueAdapter() {
            @Override
            public String value2String(double value) {
                if (value == 1) {
                    return "2015 year";
                } else if (value == 10) {
                    return "2016 year";
                } else {
                    return "2017 year";
                }
            }
        });
```

**Comment by megifernanda** [comment]
i tried this, it's just show 2017 year

i tried xAxis

**Comment by linheimx** [comment]
assume your line data is:
```
(1,10),(10,100),(20,3)
```
you can adapter 
1--->2015 year
10--->2016 year
other--->2017 year

if your data contain (2,100)
2 is other,so show the 2017 year

**Comment by megifernanda** [comment]
can you help me sir?

i want data with month

January untill december, how to make it?


i tried this
>             
             xAxis.set_ValueAdapter(new IValueAdapter() {
              @Override
            public String value2String(double value) {
                if (value == 1) {
                    return "Januari";
                }

                else if (value == 2) {
                    return "Februari";
                }
                else if (value == 3) {
                    return "MAret";
                }

                else if (value == 4) {
                    return "April";
                }

                else if (value == 5) {
                    return "Juni";
                }

            }


        });

**Comment by linheimx** [comment]
if your data like ''(1,x),(2,x),(3,x),(4,x)...''
your adapter is ok
--------------------------------
attention:
there are some way to calculate the values in axis.
if want show all label in axis,please set ``xAxis.setCalWay(Axis.CalWay.every);``
(three calcute way like:perfect,justAvg,every,you can try it )
