### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by tuyouyu** [linheimx/LChart#2]
有相关的设计图吗，用例图流程图之类的，方面新手深入了解

**Comment by linheimx** [comment]
最近在准备这方面的文章，预计这周日会发出来的。谢谢你的支持～

**Comment by tuyouyu** [comment]
好的，会关注，感谢回复

**Comment by shb695** [comment]
文章在这里：http://www.jianshu.com/p/d03ff80ad508
一篇肯定是不够的，我会继续补充  : )

**Comment by linheimx** [comment]
文章在这里：http://www.jianshu.com/p/d03ff80ad508
后续的文章我会继续发在简书里 : ）
