### ISSUE TITLE
关于单位和显示的问题

### ISSUE THREAD

**Issue by chenzhikaizg** [linheimx/LChart#4]
您这个项目的单位显示是怎么弄的，初始的单位是最小单位吗？我给添加了50条数据，数据就挤在一块成了一条棍，但是x轴的显示还是5个单位，怎么让直接显示最小的单位，只让他能滑动，不去缩放呢？

**Comment by linheimx** [comment]
1. 关于图谱是否拖拽，缩放，可拖过linechart去设置
`_lineChart.setDragable(true);
_lineChart.setScaleable(true);`
2. 关于轴线上的坐标，需要每个折线上的点对应的label都显示的话，可设置轴线label的计算方式
`xAxis.setCalWay(Axis.CalWay.every);`
