### ISSUE TITLE
关于轴坐标的问题

### ISSUE THREAD

**Issue by MagicGt** [linheimx/LChart#5]
怎么去改变轴坐标的字体颜色，大小，初始是蓝色
还有能修改轴文字类型吗，譬如12修改成12个月（double-》》String）

**Comment by MagicGt** [comment]
轴字体，大小，颜色 已经知道了

**Comment by linheimx** [comment]
给轴线设置一个adapter就可以了。
`YAxis yAxis = lineChart.get_YAxis();
yAxis.set_unit("单位：m");
yAxis.set_ValueAdapter(new IValueAdapter() {
            @Override 
            public String value2String(double value) {
                return value+“月”;
            } 
        });`

**Comment by linheimx** [comment]
给轴线设置一个adapter就可以了。
···
YAxis yAxis = lineChart.get_YAxis();
yAxis.set_unit("单位：m");
yAxis.set_ValueAdapter(new IValueAdapter() {
            @Override 
            public String value2String(double value) {
                return value+“月”;
            } 
        });
···

**Comment by linheimx** [comment]
给轴线设置一下adapter。

YAxis yAxis = lineChart.get_YAxis();
yAxis.set_ValueAdapter(new IValueAdapter() {
            @Override 
            public String value2String(double value) {
                return value+“月”;
            } 
        });

**Comment by MagicGt** [comment]
我还想问下，怎么能去除坐标负值，以0点为起点

**Comment by linheimx** [comment]
关于轴线上的的一堆label，有几种计算方式的。

需要每个折线上的点对应的label都显示的话，可设置轴线label的计算方式
`xAxis.setCalWay(Axis.CalWay.every);`
（这样的话，轴线上的一堆label是和你的折线上数据相关，就没有0啦）

**Comment by MagicGt** [comment]
你好，我并没有找到这个方法，没有暴露？

**Comment by MagicGt** [comment]
你好，我知道了，之前是1.0.9 忘记升级了，现在有这个方法了，但是我遇到了一个新的问题

**Comment by MagicGt** [comment]
现在的问题是 
我有一条是自己画上去的折线 有一条是动态获取的
首先 每条折线的count 个数不一样
用了
xAxis.setCalWay(Axis.CalWay.every); 之后出现的问题是
坐标轴只会显示动态获取的count显示，而自己画的轴坐标不显示，只是有折线

**Comment by MagicGt** [comment]
譬如，x轴本来显示到70（这是自己画出来的，0 1 2 。。。。70）
动态获取的 x轴 最大值为10（获取的为 2 4 6 10）
结果是 x轴的坐标最大显示只显示（2 4 6 10），自己画的坐标不显示

**Comment by linheimx** [comment]
`xAxis.setCalWay(Axis.CalWay.every);`我采取的策略是把第一条折线上的相关的label显示

**Comment by linheimx** [comment]
那我再考虑下多条折线。
---------
若效果还是不满意的话，可以加我的qq：917881222

**Comment by linheimx** [comment]
考虑到你这是两条折线，一条折线上一堆数据，其实这不太适合采用`Axis.CalWay.every`

**Comment by MagicGt** [comment]
我改成按多值的显示第一条，但是又出个问题，就是
譬如X轴 count 过多的话，会重叠
二是y轴 放大后Y轴会有数据不显示的问题

**Comment by linheimx** [comment]
骚年，可以加我的qq：917881222
交流更加方便
