### ISSUE TITLE
I want to have such bar for working hours. How to get this? 

### ISSUE THREAD

**Issue by Rsl717** [linheimx/LChart#7]
I have the same issue. I want to have such bar for working hours. How to get this? And whether it is possible to put a filter there ? for filtering out monthly/weekly

![](https://cloud.githubusercontent.com/assets/21261181/26141907/89d56f34-3af7-11e7-94a8-261875606e80.PNG)

**Comment by linheimx** [comment]
Sorry,LChart only support linechart.
To implement it, I advice you use MPAndroidChart:`https://github.com/PhilJay/MPAndroidChart`
Your pic looks like Horizontal-BarChart in MPAndroidChart.
Good luck!

**Comment by Rsl717** [comment]
Thank you so much !
