### ISSUE TITLE
你好，想问下怎样绘制不连续的曲线

### ISSUE THREAD

**Issue by jijingtaifeng** [linheimx/LChart#8]
假如有一组10个点的（x，y），其中有个点的y值为null，代表曲线在此处断开，接着下个有值的点继续绘制

**Comment by linheimx** [comment]
这种情况现在是不支持的。
--------------------
我会考虑加进去，预计这周日

**Comment by linheimx** [comment]
已经加上了。
你要标识 ``new Entry(3, 2).setNull_Y()``
具体的请查看demo

**Comment by jijingtaifeng** [comment]
看到了，非常感谢！
